Add cpp files
Teaching-projects/SZE-MOSZE-2020-Pied_Piper--CLOSED pull request #1
Opened 2020-09-18 17:51 UTC by csiszar197

Az első feladatot módosításait megcsináltuk.

2020-09-22 09:45 UTC, david00721 commented
@hegyhati rá tudnál nézni az első feladatunkra? Merge-re vár.

2020-09-22 11:04 UTC, hegyhati commented
@david00721 Hozzarendeltem @wajzy -t,  O fog review-t adni. Ez az elobbi mozzanat miattam allt 3 napot, amit sajnalok, de a queue-ban nem kerult ez sorra az alatt az ido alatt, amit hetvegen erre szantam. Ezert nem szerencses penteken este 8-kor bekuldeni a dolgot, hatarido elott 4 oraval.

2020-09-23 08:22 UTC, wajzy requested changes
Hozzatok szépen létre új osztályt, tanulmányozzátok a const kulcsszó használatának módját és hatását, és működjön úgy a program, ahogyan azt a feladatkiírás kéri!

2020-09-23 08:22 UTC, wajzy commented on Player.cpp
> +}
Egyrészt, ez egy elég szerencsétlen névadás, mert get-tel kezdődik a függvény neve, de nem ad vissza semmilyen értéket. Másrészt, az ilyen jellegű feladatokat jellemzően a << operátor felültöltésével szokás megoldani C++-ban.

2020-09-23 08:22 UTC, wajzy commented on Player.cpp
> +}
Szerintem itt nem azt csinálod, amit szerettél volna, mert a visszaadott érték amúgy is másolata az eredetinek, és őszintén, senkit nem érdekel, ha valaki ezt a másolatot átalakítja. Itt az objektum adattagjának értékét kellene megvédeni, de erre meg az így elhelyezett const nem alkalmas. Szerintem Te azt a sor végére akartad írni igazából, de mielőtt bármit átalakítanál, olvasd el pl. ezt:
https://www.linuxtopia.org/online_books/programming_books/thinking_in_c++/Chapter08_014.html

2020-09-23 08:22 UTC, wajzy commented on Player.cpp
> +void Player::SetInjury(float damage)
Szódával elmegy, de így nem látszik a kódon, hogy a sebzés nem akármekkora, hanem pont annyi, amennyire az ellenfél képes. Éppen ezért elegánsabb volna az ellenfél objektumát átadni, lehetőleg csak olvashatóan, és abból kiolvasni, mennyit tud sebezni, majd ennyivel csökkenteni a hp-t.

2020-09-23 08:22 UTC, wajzy commented on Source.cpp
> +void CheckHp(Player*, Player*, bool &);
Elég gyanús, hogy van több függvényetek, amik ugyanazokkal a paraméterekkel dolgoznak. Ez nekem azt sugallja, hogy a mindig átadandó értékekből lehetnének esetleg egy osztály adattagjai...

2020-09-23 08:22 UTC, wajzy commented on Source.cpp
> +	Player* player2 = new Player("Sally",45,30);
Ezek a konstans értékek meg honnan jöttek? Nem az volt a feladatkiírásban, hogy a parancssorban megadott értékeket kell használni?

2020-09-23 08:22 UTC, wajzy commented on Source.cpp
> +	Fight(player1,player2);
Most jut eszembe, függvények nevét nem szokás nagybetűvel kezdeni, mert ez azt sugallja, hogy itt egy osztályról van szó.

2020-09-23 08:22 UTC, wajzy commented on Source.cpp
> +		//2th->1th
Most komolyan, ugyanazt leírtátok kétszer, csak megcserélt sorrendben átadott paraméterekkel? Ha már úgyis mutatókkal dolgoztok, nem lett volna sokkal egyszerűbb a mutató-másolatok értékét felcserélni? Még a playerSwap változót is el lehetne hagyni...

2020-09-24 18:19 UTC, david00721 commented
@wajzy Újraírtuk az első feladatot.

2020-09-24 20:18 UTC, david00721 commented
@wajzy Közben elkészült a következő feladat is.

2020-09-24 22:30 UTC, hegyhati commented
Na ezt ne. 1 PR az 1 feature. TEssek ezt gyorsan visszacsinalni. (csinaljatok egy uj branchet errol a pontrol, hogy ne veszitsetek el, checkout vissza az initre, aztan reset addig a pontig, ami az elso feladat., aztan force push.)

2020-09-24 22:32 UTC, hegyhati commented
@oliverosz ha tudsz egyszerubb modot, ird meg, en mar elegge zombi vagyok.

2020-09-26 13:59 UTC, hegyhati reviewed
Csak az elejere neztem, volt meg benne javitani valo. Most mar a 2. feladatok mennek be, errol a reporol levesszuk a kezunket.

2020-09-26 13:59 UTC, hegyhati commented on Character.cpp
> +
es mondjuk szerintem menne 1 sorban is.

2020-09-26 13:59 UTC, hegyhati commented on Character.cpp
> +void Character::attack(Character& character)
const?

2020-09-26 13:59 UTC, hegyhati commented on Character.cpp
> +void Character::injure(int damageValue)
tul altalanos

2023-10-18 17:55 UTC, closed without merging